module.exports = function(grunt) {

	grunt.initConfig({
		srcFolder: 'topics',
		baseFolder: '.',
		pkg: grunt.file.readJSON('package.json')
	});

	/* watch */
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.config('watch', {
		options: {
			livereload: 35729,
		},
		all : {
			files: ['topics/*.js', 'Gruntfile.js']
		}
	});


	/* connect */
	grunt.loadNpmTasks('grunt-contrib-connect');
	grunt.config('connect', {
		options: {
			port: 8080,
			livereload: 35729,
			hostname: 'localhost'
		},
		livereload: {
			options: {
				open: 'http://localhost:8000/jskoans.html',
        base: '<%= baseFolder %>'
			}
		}
	});

	/* deploy gh-pages  */
	grunt.loadNpmTasks('grunt-gh-pages');
	grunt.config('gh-pages', {
		options: {
			base:  '<%= baseFolder %>' ,
			message: 'Generated by grunt gh-pages'
		},
		src: [
			'support/*',
			'topics/*',
			'jskoans.html'
		]
	});

	/* tasks  */
	grunt.loadNpmTasks('grunt-available-tasks');
	grunt.config('availabletasks', {
		tasks: {
			options: {
				/* showTasks: ['user'], */
				sort: true
			}
		}
	});

	grunt.registerTask ('deploy', ['default','gh-pages']);
	grunt.registerTask('serve', ['default','connect:livereload','watch:all']);
	grunt.registerTask('tasks', ['availabletasks']);
	grunt.registerTask('default', ['tasks']);

};